"""Update blood type constraints

Revision ID: 6444720b1d0c
Revises: f97b7e003717
Create Date: 2023-10-04 23:01:56.573968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6444720b1d0c'
down_revision = 'f97b7e003717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
