"""Added models

Revision ID: abc6292a88aa
Revises: 5e1892b16ea4
Create Date: 2023-10-04 12:20:24.126950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc6292a88aa'
down_revision = '5e1892b16ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_name', sa.String(), nullable=True),
    sa.Column('blood_type', sa.String(), nullable=True),
    sa.CheckConstraint("blood_type IN ('A', 'B', 'AB', 'O')", name='blood_types'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donor_hospitals',
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('donor_id', 'hospital_id')
    )
    op.create_table('recepients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recepient_name', sa.String(), nullable=True),
    sa.Column('blood_type', sa.String(), nullable=True),
    sa.Column('hospital_id', sa.String(), nullable=True),
    sa.CheckConstraint("blood_type IN ('A', 'B', 'AB', 'O')", name='blood_types'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('donation_date', sa.DateTime(), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('bloodreceiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bloodreceiver_id'], ['recepients.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donations')
    op.drop_table('recepients')
    op.drop_table('donor_hospitals')
    op.drop_table('hospitals')
    op.drop_table('donors')
    # ### end Alembic commands ###
