"""Update blood type constraints

Revision ID: daace8b51b55
Revises: ff61fe467c7b
Create Date: 2023-10-04 23:08:58.620120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daace8b51b55'
down_revision = 'ff61fe467c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
