"""Update blood type constraints

Revision ID: ef0b12eacdf5
Revises: a476644f208d
Create Date: 2023-10-04 22:46:19.376828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0b12eacdf5'
down_revision = 'a476644f208d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
