"""Update blood type constraints

Revision ID: f97b7e003717
Revises: ef0b12eacdf5
Create Date: 2023-10-04 22:51:34.645140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97b7e003717'
down_revision = 'ef0b12eacdf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
